### ISSUE TITLE
Missing "he/him" or "her/she" text

### ISSUE THREAD

**Issue by rfirebaugh** [mozilla-iam/dino-park-front-end#47] opened 2018-10-13 04:27 UTC
Missing "he/him" or "her/she" text. Unsure if its missing placeholder data or not functioning. See attached screenshot.

<img width="293" alt="screen shot 2018-10-12 at 9 25 27 pm" src="https://user-images.githubusercontent.com/43189936/46901285-957fce80-ce65-11e8-8945-8fe07faeb256.png">

**Comment by hidde** [comment] 2018-10-14 20:38
Not all profiles have this data, this is a content/data issue. Closing this issue as it is not a bug in the front-end.

**Closed by hidde** 2018-10-14 20:38 UTC
