### ISSUE TITLE
Safari v12 white background does not continue to bottom of browser

### ISSUE THREAD

**Issue by rfirebaugh** [mozilla-iam/dino-park-front-end#57] opened 2018-10-13 04:55 UTC
In Safari browser version 12, the white background does not continue to bottom of browser, instead cuts off and you can see transparency. See attached image.

<img width="523" alt="screen shot 2018-10-12 at 9 51 25 pm" src="https://user-images.githubusercontent.com/43189936/46901474-784cff00-ce69-11e8-97d3-8b7f8199ffb9.png">

**Comment by hidde** [comment] 2018-10-15 11:44
This is a duplicate of #60  closing this issue.

**Closed by hidde** 2018-10-15 11:44 UTC
Labels: invalid
