### ISSUE TITLE
Profile are not public anymore, require to login (js error in console)

### ISSUE THREAD

**Issue by Mte90** [mozilla-iam/dino-park-front-end#654] opened 2021-05-26 10:18 UTC
**Describe the bug**
Mozillian had the feature that a profile is public and as logged you can see more information.

**To Reproduce**
1. Go to 'https://people.mozilla.org/p/Mte90'
2. As non logged

**Expected behavior**
See the profile.

**Screenshots**
![Screenshot_20210526_121752](https://user-images.githubusercontent.com/403283/119643765-710d7080-be1c-11eb-8e74-e45c99e5301d.png)

**Comment by m3Lith** [comment] 2021-08-23 19:03
Why was this labeled with `wontfix`?

**Comment by mhoye** [comment] 2021-08-24 14:47
Hi, everyone - my apologies for the inconvenience of non-public profiles, but we're in the slow process of working through filtering out a _lot_ of spam that's found its way in to this this thing, a process that is unfortunately mostly manual. Once that's sorted out we will (I hope) reopen public profiles, with enrolment options tightened down appropriately. 

I don't have good estimate of when this work will be wrapped up, for which I apologize, and I hope this is only a modest inconvenience. (Unless you were using this service to sell timeshares, narcotics, bitcoin, online gambling, essay-writing services and arranged marriages, in which case I hope it's a huge inconvenience for you and somebody pours sand in your underpants every day.)

**Comment by Mte90** [comment] 2021-08-24 19:11
In Mozillians there was similar issue and they fixed with akismet integrations and also with a report button. I know because I reported over 600+ accounts on that platform.
I guess that the spam issue should be handed by the Auth service used for login?

The issue to me is that there is a JS error in console without an alert like you need to login to see the profile.

**Comment by Mte90** [comment] 2021-09-08 10:49
I think that we can close this as now if your are not logged you are forced to login to see a profile.

I don't like this approach as this was helpful to show the profiles also to people that are not using Firefox Accounts or Firefox users.

**Comment by gene1wood** [comment] 2021-09-13 19:59
> I don't like this approach as this was helpful to show the profiles also to people that are not using Firefox Accounts or Firefox users.

Do keep in mind, you need not be a Firefox Accounts or Firefox user to login to people.mozilla.org (you can login with any identity provider including just an email address

**Comment by m3Lith** [comment] 2021-09-13 20:26
That's not any better. The idea of a public profile, from how I understand it, should be to share it with other people with no friction at all (like a public profile on social media, with limited details), just by clicking a link. Forcing to sign in, by whatever means, should only be required if any interaction would take place.

Before this I had my profile linked when mentioning my hobbies/activities to people. I don't think many would try to login. I certainly would not.

**Comment by wsmwk** [comment] 2022-04-17 16:32
I was hoping to use this.  What are people using as an alternative for public info/personas?

**Comment by wsmwk** [comment] 2022-04-17 16:36
related to issue 179?

**Comment by wsmwk** [comment] 2022-06-05 14:49
@mhoye seems like this capability would be important for an open source organizatino.  Is there an alternative?  ^

**Comment by floatingatoll** [comment] 2022-06-05 17:05
Hi, I'm the IAM/SSO lead. Given the participation of bad actors in the circumstances leading to this issue and other non-public information, I'm not able to address your question openly here. mhoye and I are NDA'd staff; other staff are invited to bring any concerns to us by email if this is impacting their work somehow.

As the closure of this service to anonymous visitors is currently by design, I'm going to close this ticket for the time being. Discussion will continue about what we can do about this problem regardless.

This ticket closure is neither indication of a change in position, nor an indication of any new finality.

**Closed** 2022-06-05 17:05 UTC
Labels: wontfix
